sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
                    - Symfony\Component\Security\Core\Exception\AccessDeniedException
                    - InvalidArgumentException
                    - UnexpectedValueException
